### ISSUE TITLE
nice work

### ISSUE THREAD

**Issue by arcanoix** [Splode/open-trivia-app#3] opened 2017-11-09 10:41 UTC
Good job I have a problem when I try to make npm run dev me launches an error in question specifically says true is a reserved word.

if (choice. answer) {)
        // Score correctly
        this. $store. commit (' score', {**true**, mode});  <-------
        Call down the stars!
        this. $store. dispatch (' starPower');
      } else {
        // Score incorrectly
        this. $store. commit (' score', {**false**, mode});  <-------
      }

**Comment by Splode** [comment] 2017-11-09 16:05
This bug was caused by using the object property shorthand in conjunction with the reserved word, `true`. This was resolved by changing the `score` mutation in the `Questions` component 
**from** 
```
this.$store.commit('score', {true, mode});
```
**to**

```
this.$store.commit('score', {true: true, mode});
````

Thanks!

**Closed as completed by Splode** 2017-11-09 16:05 UTC
